export const ACTION = {
  SELECT_DATES: 'SELECT_DATES',
  SELECT_PRICE: 'SELECT_PRICE',
  SELECT_GUESTS: 'SELECT_GUESTS',
  FOCUS_FIELD: 'FOCUS_FIELD',
  BLUR_FIELD: 'BLUR_FIELD',
  CLICK_FIELD: 'CLICK_FIELD',
  CLOSE_MODAL: 'CLOSE_MODAL',
};
