export const ACTION = {
  PICK_DATE: 'PICK_DATE',
  DELETE_CHECK_IN: 'DELETE_CHECK_IN',
  DELETE_CHECK_OUT: 'DELETE_CHECK_OUT',
  SELECT_PRICE: 'SELECT_PRICE',
  SELECT_GUESTS: 'SELECT_GUESTS',
  FOCUS_FIELD: 'FOCUS_FIELD',
  BLUR_FIELD: 'BLUR_FIELD',
  CLICK_FIELD: 'CLICK_FIELD',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_PATH: 'SET_PATH',
  CLICK_MODAL: 'CLICK_MODAL',
};
